/*
 * This file is generated by jOOQ.
 */
package jooq;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import jooq.tables.Heroes;
import jooq.tables.records.HeroesRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HeroesRecord> HEROES_PKEY = Internal.createUniqueKey(Heroes.HEROES, DSL.name("heroes_pkey"), new TableField[] { Heroes.HEROES.HERO_ID }, true);
}
