/*
 * This file is generated by jOOQ.
 */
package jooq;


import jooq.tables.Heroes;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.heroes</code>.
     */
    public static final Heroes HEROES = Heroes.HEROES;
}
