/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import jooq.tables.Heroes;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HeroesRecord extends UpdatableRecordImpl<HeroesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.heroes.hero_id</code>.
     */
    public void setHeroId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.heroes.hero_id</code>.
     */
    public Integer getHeroId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.heroes.hero_name</code>.
     */
    public void setHeroName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.heroes.hero_name</code>.
     */
    public String getHeroName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Heroes.HEROES.HERO_ID;
    }

    @Override
    public Field<String> field2() {
        return Heroes.HEROES.HERO_NAME;
    }

    @Override
    public Integer component1() {
        return getHeroId();
    }

    @Override
    public String component2() {
        return getHeroName();
    }

    @Override
    public Integer value1() {
        return getHeroId();
    }

    @Override
    public String value2() {
        return getHeroName();
    }

    @Override
    public HeroesRecord value1(Integer value) {
        setHeroId(value);
        return this;
    }

    @Override
    public HeroesRecord value2(String value) {
        setHeroName(value);
        return this;
    }

    @Override
    public HeroesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HeroesRecord
     */
    public HeroesRecord() {
        super(Heroes.HEROES);
    }

    /**
     * Create a detached, initialised HeroesRecord
     */
    public HeroesRecord(Integer heroId, String heroName) {
        super(Heroes.HEROES);

        setHeroId(heroId);
        setHeroName(heroName);
    }
}
