/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import jooq.Keys;
import jooq.Public;
import jooq.tables.records.HeroesRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Heroes extends TableImpl<HeroesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.heroes</code>
     */
    public static final Heroes HEROES = new Heroes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HeroesRecord> getRecordType() {
        return HeroesRecord.class;
    }

    /**
     * The column <code>public.heroes.hero_id</code>.
     */
    public final TableField<HeroesRecord, Integer> HERO_ID = createField(DSL.name("hero_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.heroes.hero_name</code>.
     */
    public final TableField<HeroesRecord, String> HERO_NAME = createField(DSL.name("hero_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private Heroes(Name alias, Table<HeroesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Heroes(Name alias, Table<HeroesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.heroes</code> table reference
     */
    public Heroes(String alias) {
        this(DSL.name(alias), HEROES);
    }

    /**
     * Create an aliased <code>public.heroes</code> table reference
     */
    public Heroes(Name alias) {
        this(alias, HEROES);
    }

    /**
     * Create a <code>public.heroes</code> table reference
     */
    public Heroes() {
        this(DSL.name("heroes"), null);
    }

    public <O extends Record> Heroes(Table<O> child, ForeignKey<O, HeroesRecord> key) {
        super(child, key, HEROES);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<HeroesRecord, Integer> getIdentity() {
        return (Identity<HeroesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<HeroesRecord> getPrimaryKey() {
        return Keys.HEROES_PKEY;
    }

    @Override
    public Heroes as(String alias) {
        return new Heroes(DSL.name(alias), this);
    }

    @Override
    public Heroes as(Name alias) {
        return new Heroes(alias, this);
    }

    @Override
    public Heroes as(Table<?> alias) {
        return new Heroes(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Heroes rename(String name) {
        return new Heroes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Heroes rename(Name name) {
        return new Heroes(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Heroes rename(Table<?> name) {
        return new Heroes(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
